---
- name: Add users and encrypt file
  hosts: test
  gather_facts: false
  vars_files:
    - ./credentials/user_credentials.yaml
  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{ user.name }}"
        password: "{{ user.password | password_hash('sha512')}}"
        state: present
        createhome: yes 
        comment: 'Ansible-generated user'
      loop:  "{{ users }}"
      loop_control:
        loop_var: user
        pause: 5
      no_log: true






    



